language: python

python:
  - "3.8"


install:
   - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  # Run Black formatter
  - black --check .

  # Run Flake8 linter
  - flake8 --extend-ignore E501,F401,F811
  # Run Django tests
  - coverage run manage.py test
  
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "polls"
  env: "env-niko"
  on:
    branch: main